import {
  existsSync,
  writeFileSync,
  unlinkSync,
  mkdirSync,
  chmodSync,
} from "node:fs";
import { homedir } from "node:os";
import { join, dirname } from "node:path";
import { execSync } from "node:child_process";
import { USEAI_DIR, DAEMON_LOG_FILE } from "@devness/useai-storage/paths";
import { resolveNpxPath, buildServicePath } from "./resolve-npx.js";

// Injected by tsup at bundle time from packages/useai/package.json. We pin the
// autostart launcher to *this* version so a future bad publish on npm can't
// take down everyone's daemon. Users opt into upgrades with `useai update`.
declare const __VERSION__: string | undefined;
const VERSION = typeof __VERSION__ !== "undefined" ? __VERSION__ : "dev";

const HOME = homedir();

// Launcher script that the autostart service points at instead of `npx`
// directly. This is purely cosmetic: macOS Login Items shows the executable
// name from ProgramArguments[0], so pointing at `~/.useai/bin/useai-daemon`
// makes the entry read "useai-daemon" instead of "npx" with a generic JS icon.
// The script just execs npx with our package and the hidden daemon-run command.
const LAUNCHER_DIR = join(USEAI_DIR, "bin");
const LAUNCHER_PATH = join(LAUNCHER_DIR, "useai-daemon");

function launcherScript(npxPath: string, servicePath: string): string {
  // Pin to the current package version (no @dev, no --prefer-online).
  // npx will install once and use its on-disk cache for every subsequent
  // restart, so the daemon does not depend on registry availability after
  // first run. Users update by running `useai update`, which re-installs
  // the autostart service against the new version.
  //
  // Dev mode: when VERSION is the "dev" sentinel (running from a local
  // tsc build with no __VERSION__ injected), there is no published
  // `@devness/useai@dev` on npm — the npx form would fail with ETARGET
  // and systemd would loop until it hit the restart limit. Instead, point
  // the launcher at the same local CLI script that wrote this file
  // (process.argv[1] is the absolute path of the running CLI).
  //
  // We deliberately do NOT pin USEAI_PORT here — the daemon reads its
  // preferred port from `~/.useai/config.json` (sticky across restarts) and
  // falls back to a probe range if 19200 is taken. Hardcoding USEAI_PORT
  // would short-circuit that resolver and re-introduce the port-collision
  // failure mode P2.1 was meant to fix.
  const isDev = VERSION === "dev";
  const execLine = isDev
    ? `exec node "${process.argv[1] ?? ""}" daemon-run`
    : `exec "${npxPath}" -y @devness/useai@${VERSION} daemon-run`;
  return `#!/bin/sh
# useai-daemon — launcher for the useai background daemon.
# Generated by \`useai start --boot\` from useai@${VERSION}.
# Do not edit by hand; re-run the install command to regenerate.
export PATH="${servicePath}"
${execLine}
`;
}

function writeLauncher(npxPath: string, servicePath: string): void {
  mkdirSync(LAUNCHER_DIR, { recursive: true });
  writeFileSync(LAUNCHER_PATH, launcherScript(npxPath, servicePath), "utf-8");
  chmodSync(LAUNCHER_PATH, 0o755);
}

function removeLauncher(): void {
  try {
    if (existsSync(LAUNCHER_PATH)) unlinkSync(LAUNCHER_PATH);
  } catch {
    /* ignore */
  }
}

// ---------------------------------------------------------------------------
// macOS — launchd
// ---------------------------------------------------------------------------

const LAUNCHD_LABEL = "dev.useai.daemon";
const LAUNCHD_PLIST_PATH = join(
  HOME,
  "Library",
  "LaunchAgents",
  `${LAUNCHD_LABEL}.plist`,
);

function launchdDomain(): string {
  try {
    const uid = execSync("id -u", { encoding: "utf-8" }).trim();
    return `gui/${uid}`;
  } catch {
    return `gui/${process.getuid?.() ?? 501}`;
  }
}

function launchdServiceTarget(): string {
  return `${launchdDomain()}/${LAUNCHD_LABEL}`;
}

function launchdPlist(): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${LAUNCHER_PATH}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>ExitTimeOut</key>
  <integer>10</integer>
  <key>ProcessType</key>
  <string>Background</string>
  <key>StandardOutPath</key>
  <string>${DAEMON_LOG_FILE}</string>
  <key>StandardErrorPath</key>
  <string>${DAEMON_LOG_FILE}</string>
</dict>
</plist>
`;
}

/**
 * Wait up to `timeoutMs` for the launchd service to fully tear down after a
 * `bootout`. Re-bootstrapping while the previous instance is still in `removing`
 * or `xpcproxy` state races with launchd and fails with the unhelpful generic
 * "Bootstrap failed: 5: Input/output error". Polling `launchctl print` until
 * the service is unknown lets `bootstrap` succeed first try.
 */
function waitForLaunchdGone(target: string, timeoutMs = 5_000): void {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      execSync(`launchctl print ${target}`, {
        stdio: ["ignore", "ignore", "ignore"],
      });
    } catch {
      return; // print failed → service is gone, safe to bootstrap
    }
    // Service still registered. Brief pause and re-check.
    execSync("sleep 0.2");
  }
}

/**
 * Run `launchctl bootstrap`, capturing stderr so the user sees the actual
 * launchd diagnostic on failure (not just "Command failed: launchctl
 * bootstrap …"). Retries once after a short delay because the most common
 * failure is a race against the previous instance still tearing down.
 */
function launchctlBootstrap(domain: string, plistPath: string): void {
  const cmd = `launchctl bootstrap ${domain} "${plistPath}"`;
  try {
    execSync(cmd, { stdio: ["ignore", "ignore", "pipe"] });
    return;
  } catch (err: unknown) {
    const stderr =
      err instanceof Error && "stderr" in err
        ? String((err as { stderr: Buffer | string }).stderr).trim()
        : "";

    // Brief pause then retry — covers the common race where a previous
    // instance hasn't fully unloaded yet.
    execSync("sleep 1.5");
    try {
      execSync(cmd, { stdio: ["ignore", "ignore", "pipe"] });
      return;
    } catch (retryErr: unknown) {
      const retryStderr =
        retryErr instanceof Error && "stderr" in retryErr
          ? String((retryErr as { stderr: Buffer | string }).stderr).trim()
          : "";
      const detail =
        retryStderr || stderr || "(no error output from launchctl)";
      throw new Error(`launchctl bootstrap failed: ${detail}`);
    }
  }
}

function installMacos(): void {
  const npxPath = resolveNpxPath();
  const servicePath = buildServicePath();
  const target = launchdServiceTarget();
  const domain = launchdDomain();

  writeLauncher(npxPath, servicePath);

  mkdirSync(dirname(LAUNCHD_PLIST_PATH), { recursive: true });
  writeFileSync(LAUNCHD_PLIST_PATH, launchdPlist(), "utf-8");

  // Bootout first so a re-install picks up plist changes (idempotent).
  try {
    execSync(`launchctl bootout ${target}`, {
      stdio: ["ignore", "ignore", "ignore"],
    });
  } catch {
    /* ignore */
  }

  // Wait for the previous instance to fully tear down before bootstrapping.
  // Otherwise `bootstrap` races with launchd's removal and fails generically.
  waitForLaunchdGone(target);

  // Clear any disabled state from a prior crash-loop throttle.
  try {
    execSync(`launchctl enable ${target}`, {
      stdio: ["ignore", "ignore", "ignore"],
    });
  } catch {
    /* ignore */
  }

  launchctlBootstrap(domain, LAUNCHD_PLIST_PATH);
}

function uninstallMacos(): void {
  const target = launchdServiceTarget();
  try {
    execSync(`launchctl bootout ${target} 2>/dev/null`, { stdio: "ignore" });
  } catch {
    /* ignore */
  }
  try {
    if (existsSync(LAUNCHD_PLIST_PATH)) unlinkSync(LAUNCHD_PLIST_PATH);
  } catch {
    /* ignore */
  }
  removeLauncher();
}

// ---------------------------------------------------------------------------
// Linux — systemd user unit
// ---------------------------------------------------------------------------

const SYSTEMD_UNIT_NAME = "useai-daemon.service";
const SYSTEMD_UNIT_PATH = join(
  HOME,
  ".config",
  "systemd",
  "user",
  SYSTEMD_UNIT_NAME,
);

function systemdUnit(): string {
  return `[Unit]
Description=useai daemon
After=network.target
StartLimitBurst=5
StartLimitIntervalSec=60

[Service]
Type=simple
ExecStart=${LAUNCHER_PATH}
Restart=on-failure
RestartSec=10
StandardOutput=append:${DAEMON_LOG_FILE}
StandardError=append:${DAEMON_LOG_FILE}

[Install]
WantedBy=default.target
`;
}

function installLinux(): void {
  const npxPath = resolveNpxPath();
  const servicePath = buildServicePath();

  //npx path and /bin path. and create the launch/restart script.
  writeLauncher(npxPath, servicePath);

  mkdirSync(dirname(SYSTEMD_UNIT_PATH), { recursive: true });
  writeFileSync(SYSTEMD_UNIT_PATH, systemdUnit(), "utf-8");

  try {
    //resets the resetCount no.
    execSync(`systemctl --user reset-failed ${SYSTEMD_UNIT_NAME}`, {
      stdio: "ignore",
    });
  } catch {
    /* ignore */
  }
  //Re-read the fresh unit files.
  execSync("systemctl --user daemon-reload", { stdio: "ignore" });
  //Run daemon launcher script
  execSync(`systemctl --user enable --now ${SYSTEMD_UNIT_NAME}`, {
    stdio: "ignore",
  });
}

function uninstallLinux(): void {
  try {
    execSync(`systemctl --user disable --now ${SYSTEMD_UNIT_NAME}`, {
      stdio: "ignore",
    });
  } catch {
    /* ignore */
  }
  try {
    if (existsSync(SYSTEMD_UNIT_PATH)) unlinkSync(SYSTEMD_UNIT_PATH);
  } catch {
    /* ignore */
  }
  try {
    execSync("systemctl --user daemon-reload", { stdio: "ignore" });
  } catch {
    /* ignore */
  }
  removeLauncher();
}

// ---------------------------------------------------------------------------
// Windows — Startup-folder VBScript (per-user, hidden, runs on logon)
// ---------------------------------------------------------------------------
//
// Why a .vbs in the Startup folder instead of Task Scheduler:
//   * No schtasks, no UTF-16 XML, no admin-prompt risk on locked-down machines.
//   * WScript.Shell.Run cmd, 0, False launches the daemon fully hidden — no
//     flashing cmd console window, no taskbar entry. A .cmd dropped in
//     Startup (or run behind a schtasks task) leaves a console window visible
//     for the daemon's entire lifetime; .vbs does not.
//   * Uninstall is a single unlinkSync.
//
// Tradeoff vs launchd KeepAlive / systemd Restart=on-failure: this approach
// does NOT auto-relaunch the daemon if it crashes mid-session. It only fires
// at logon. The CLI's `ensureDaemonRunning` covers crash recovery on next
// MCP call, which is enough for a session tracker.

const VBS_NAME = "useai-daemon.vbs";

function startupDirWin(): string {
  const appData = process.env["APPDATA"];
  if (!appData)
    throw new Error("Cannot install autostart: %APPDATA% is not set.");
  return join(
    appData,
    "Microsoft",
    "Windows",
    "Start Menu",
    "Programs",
    "Startup",
  );
}

function vbsPathWin(): string {
  return join(startupDirWin(), VBS_NAME);
}

function resolveUseaiPathWin(): string {
  // Prefer the .cmd shim that `npm i -g` installs alongside node. It is what
  // ends up on PATH and what WScript.Shell.Run can launch directly without
  // needing to spawn cmd.exe explicitly.
  try {
    const out = execSync("where useai.cmd", {
      stdio: ["pipe", "pipe", "ignore"],
      encoding: "utf-8",
    }).trim();
    if (out) return out.split("\n")[0]!.trim();
  } catch {
    /* not found */
  }
  try {
    const out = execSync("where useai", {
      stdio: ["pipe", "pipe", "ignore"],
      encoding: "utf-8",
    }).trim();
    if (out) {
      const first = out.split("\n")[0]!.trim();
      if (!first.toLowerCase().endsWith(".cmd")) {
        const cmdPath = first + ".cmd";
        if (existsSync(cmdPath)) return cmdPath;
      }
      return first;
    }
  } catch {
    /* not found */
  }
  throw new Error(
    "Could not find the `useai` command on PATH. Install with `npm i -g @devness/useai` first.",
  );
}

function vbsScript(command: string): string {
  // In a VBScript string literal embedded double-quotes are escaped by
  // doubling them ("" inside a "...."). The caller has already shaped
  // `command` as the exact post-Run-call string we want WScript.Shell to
  // execute (e.g. `""C:\…\useai.cmd"" daemon-run` for prod, or
  // `node ""C:\…\dist\cli\index.js"" daemon-run` for a local dev build).
  return [
    `' useai-daemon launcher — runs the daemon hidden on every logon.`,
    `' Generated by useai. Delete this file (or run \`useai mcp remove\`) to disable.`,
    `CreateObject("WScript.Shell").Run "${command}", 0, False`,
    ``,
  ].join("\r\n");
}

function installWindows(): void {
  // Dev mode: same rationale as Linux/macOS — when VERSION is the "dev"
  // sentinel there is no published `@devness/useai@dev`, so we can't
  // route through a globally-installed `useai.cmd` (it would be the wrong
  // version anyway). Run the local CLI directly via node.
  const isDev = VERSION === "dev";
  const command = isDev
    ? `node ""${process.argv[1] ?? ""}"" daemon-run`
    : `""${resolveUseaiPathWin()}"" daemon-run`;
  const target = vbsPathWin();
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, vbsScript(command), "utf-8");

  // Start the daemon now so setup doesn't have to wait for the next logon.
  // Non-fatal — the .vbs is in place and will fire on next sign-in regardless.
  try {
    execSync(`wscript "${target}"`, { stdio: "ignore" });
  } catch {
    /* ignore */
  }
}

function uninstallWindows(): void {
  try {
    const target = vbsPathWin();
    if (existsSync(target)) unlinkSync(target);
  } catch {
    /* ignore */
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export type AutostartPlatform = "darwin" | "linux" | "win32";

export function getAutostartPlatform(): AutostartPlatform | null {
  if (process.platform === "darwin") return "darwin";
  if (process.platform === "linux") return "linux";
  if (process.platform === "win32") return "win32";
  return null;
}

/**
 * Install (and start) the autostart service for the current platform.
 *
 * On macOS this writes a launchd plist to `~/Library/LaunchAgents/` and
 * bootstraps it so the daemon starts immediately and on every login.
 * On Linux this writes a systemd user unit to `~/.config/systemd/user/`
 * and runs `enable --now` to start and persist it.
 * On Windows this drops a hidden VBScript in the per-user Startup folder
 * (`%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup`) that runs
 * `useai daemon-run` with no visible console window on every logon.
 *
 * Idempotent: re-running re-applies the latest plist/unit/script content.
 */
export function installAutostart(): void {
  const platform = getAutostartPlatform();
  if (!platform)
    throw new Error(`Autostart not supported on ${process.platform}`);

  if (platform === "darwin") {
    installMacos();
    return;
  }

  if (platform === "linux") {
    installLinux();
    return;
  }

  if (platform === "win32") {
    installWindows();
  }
}

export function uninstallAutostart(): void {
  const platform = getAutostartPlatform();
  if (platform === "darwin") {
    uninstallMacos();
    return;
  }
  if (platform === "linux") {
    uninstallLinux();
    return;
  }
  if (platform === "win32") {
    uninstallWindows();
  }
}

export function isAutostartEnabled(): boolean {
  const platform = getAutostartPlatform();
  if (platform === "darwin") return existsSync(LAUNCHD_PLIST_PATH);
  if (platform === "linux") return existsSync(SYSTEMD_UNIT_PATH);
  if (platform === "win32") return existsSync(vbsPathWin());
  return false;
}
